### ISSUE TITLE
[Suggestion] 3D Wreath 

### ISSUE THREAD

**Issue by SinisterGladiator** [MehVahdJukaar/SnowySpirit#19]
I feel like it could look better than 2d

**Comment by MehVahdJukaar** [comment]
2d allows it to have way more default. if it was 3d it would have to use a few cubes to follow mc style so I would likely make a hollow rectangle shape and I dont think it would look any good. If you want tho you can make any kind or resource packs for it that changes the model and upload it to curseforge too
