### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by JellyBubb1e** [MehVahdJukaar/SnowySpirit#21]
<details>
<summary>mod list</summary>
<pre><code>
	- adorn 3.6.1+1.19
	- adventurez 1.4.16
	- amecs 1.3.8+mc.1.19-rc2
	- appleskin 2.4.1+mc1.19
	- architectury 6.2.46
	- attributefix 17.1.3
	- awesomedungeon 3.0.0
	- badpackets 0.2.0
	- barteringstation 4.0.0
	- bclib 2.1.0
	- betteradvancements 0.2.2.142
	- betterbeds 1.2.0
	- betterend 2.1.0
	- betternether 7.1.0
	- blossom 1.0.5
	- blue_endless_jankson 1.2.1 via owo
	- bookshelf 16.1.5
	- bosses_of_mass_destruction 1.4.2-1.19
	- bountiful 3.0.0
	- byg 2.0.0.11
	- capybara 1.0.8
	- cardinal-components 5.0.2
	- cardinal-components-base 5.0.2 via cardinal-components
	- cardinal-components-block 5.0.2 via cardinal-components
	- cardinal-components-chunk 5.0.2 via cardinal-components
	- cardinal-components-entity 5.0.2 via cardinal-components
	- cardinal-components-item 5.0.2 via cardinal-components
	- cardinal-components-level 5.0.2 via cardinal-components
	- cardinal-components-scoreboard 5.0.2 via cardinal-components
	- cardinal-components-world 5.0.2 via cardinal-components
	- charm 4.4.4
	- cloth-api 4.0.65
	- cloth-basic-math 0.6.1 via cloth-api
	- cloth-client-events-v0 4.0.65 via cloth-api
	- cloth-common-events-v1 4.0.65 via cloth-api
	- cloth-config 8.2.88
	- cloth-utils-v1 4.0.65 via cloth-api
	- clumps 9.0.0+11
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 19 via geckolib3
	- com_eliotlash_molang_molang 19 via geckolib3
	- com_github_llamalad7_mixinextras 0.1.0-rc5 via porting_lib_base
	- com_google_code_findbugs_jsr305 3.0.2 via twilightforest
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- comforts 6.0.1+1.19.2
	- completeconfig 2.0.0
	- completeconfig-base 2.0.0 via completeconfig
	- cosmetic-armor 1.4.0
	- crawl 0.11.1
	- creativecore 2.8.5
	- creeperoverhaul 2.0.3
	- cutehermitcrabs 2.0.3-1.19.2
	- dawn 3.5.0
	- debugify 2.7.1
	- diagonalfences 4.2.1
	- dragonloot 1.1.2
	- dungeons_arise 2.1.51
	- earthtojavamobs 1.9.3
	- ecologics 2.1.10
	- edenring 0.6.4
	- endgoblintraders 1.5.1
	- enhancedcelestials 2.1.0.1
	- everycomp 1.19.2-2.0.4
	- expandeddelight 0.2.2
	- fabric-api 0.62.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.3.1+624e468e90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.2.0+b598f4ac90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
	- fabric-item-groups-v0 0.3.30+93d8cb8290 via fabric-api
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
	- fabric-loot-api-v2 1.1.4+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.7+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.15+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
	- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.12+93d8cb8290 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via shoppy
	- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.12+a29562c890 via fabric-api
	- fabric-resource-loader-v0 0.7.0+93d8cb8290 via fabric-api
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
	- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fake-player-api 0.4.0 via the_bumblezone
	- fallingtree 3.10.0
	- farmersdelight 1.19-1.3.3
	- farmersknives 2.1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- forgeconfigapiport 4.2.6
	- frame 0.26.1+1.19-fabric
	- frame-api-base 0.2.1+906ebc04a9 via frame
	- frame-blocks-v0 0.1.3+233e7428a9 via frame
	- frame-config-v0 0.3.1+0fa45150a9 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-enchantments-v0 0.1.0+4093105da9 via frame
	- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
	- frame-items-v0 0.1.3+906ebc04a9 via frame
	- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
	- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
	- frame-rendering-v0 0.1.5+906ebc04a9 via frame
	- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
	- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
	- frame-woods-v0 0.2.1+6a33fbada9 via frame
	- friendsandfoes 1.5.10
	- fwaystones 3.0.4+mc1.19.2
	- galosphere 1.19.1-1.1.2
	- geckolib3 3.1.20
	- geodes 1.5.1
	- go-fish 1.6.0-1.19.1
	- goblintraders 1.5.2
	- goodall 1.1.1
	- guardvillagers 1.19-1.0.16
	- hauntedharvest 1.19.2-2.0.0
	- hedgehog 1.19-1.0.0
	- horseexpert 4.0.0
	- jade 8.2.1
	- java 18
	- javax_annotation_javax_annotation-api 1.3.2 via twilightforest
	- kambrik 4.0-1.19.2
	- krypton 0.2.1
	- lazydfu 0.1.3
	- libraryferret 3.0.0
	- lithium 0.8.3
	- lovely_snails 1.1.0+1.19
	- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
	- mcwbridges 2.0.4
	- mcwfences 1.0.6
	- mcwlights 1.0.4
	- midnightlib 0.6.0 via the_bumblezone
	- minecraft 1.19.2
	- mm 2.3 via crawl
	- mobscarecrow 2.2.1-1.19.1
	- moonlight 1.19.2-2.0.30
	- more_babies 1.0.0
	- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
	- mvs 2.5.8
	- naturalist 2.1.1
	- naturescompass 1.19.2-2.0.4-fabric
	- nears 1.2.3
	- nochatreports 1.19.2-v1.13.5
	- octo-economy-api 1.0.1 via shoppy
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- owo 0.8.2+1.19
	- paintings 10.2.1.0
	- patchouli 1.19.2-76-FABRIC
	- pickupnotifier 4.2.0
	- polymorph 0.45.0+1.19.2
	- porting_lib_accessors 2.0.547+1.19.2 via porting_lib_extensions
	- porting_lib_attributes 2.0.547+1.19.2 via porting_lib_extensions
	- porting_lib_base 2.0.547+1.19.2 via template
	- porting_lib_common 2.0.547+1.19.2 via porting_lib_transfer
	- porting_lib_constants 2.0.547+1.19.2 via porting_lib_transfer
	- porting_lib_entity 2.0.547+1.19.2 via template
	- porting_lib_extensions 2.0.547+1.19.2 via porting_lib_model_loader
	- porting_lib_model_generators 2.0.547+1.19.2 via template
	- porting_lib_model_loader 2.0.547+1.19.2 via porting_lib_obj_loader
	- porting_lib_models 2.0.547+1.19.2 via template
	- porting_lib_networking 2.0.547+1.19.2 via template
	- porting_lib_obj_loader 2.0.547+1.19.2 via template
	- porting_lib_tags 2.0.547+1.19.2 via template
	- porting_lib_transfer 2.0.547+1.19.2 via template
	- promenade 2.7.1
	- puzzleslib 4.3.8
	- ratsmischief 1.4.0
	- reach-entity-attributes 2.3.0 via twilightforest
	- repurposed_structures 6.1.1+1.19
	- seasons 1.4-BETA+1.19
	- serialization_hooks 0.3.22 via twilightforest
	- shoppy 1.0.5
	- skyvillages 1.0.2.1
	- snowyspirit 1.19.2-2.0.1
	- spark 1.9.40
	- spectrelib 0.10.0+1.19 via comforts
	- spirit 2.1.12
	- sprout 1.4.3
	- starlight 1.1.1+fabric.ae22326
	- stoneholm 1.4.4
	- strawgolem 2.0.0b2
	- supplementaries 1.19.2-2.2.3
	- t_and_t 1.8.2
	- template 2.0.547+1.19.2 via twilightforest
	- terrablender 2.0.1.127
	- terraform-shapes-api-v1 4.0.0 via promenade
	- the_bumblezone 6.1.13+1.19.2
	- thonkutil 2.15.4+1.19
	- thonkutil-base 1.13.2+4a8c408a57 via thonkutil
	- thonkutil-capes-v1 1.4.2+3eb2749857 via thonkutil
	- thonkutil-customization-v1 1.1.2+8ff533c957 via thonkutil
	- thonkutil-legacy 1.1.2+5d4263f557 via thonkutil
	- thonkutil-modchecker-v1 1.1.3+bd4b387957 via thonkutil
	- thonkutil-potions-v0 1.5.2+8ff533c957 via thonkutil
	- thonkutil-trades-v1 1.2.2+8ff533c957 via thonkutil
	- tooltiprareness 1.0.7
	- travelersbackpack 1.19.2-8.2.1
	- trinkets 3.4.0
	- tumbleweed 0.5.1
	- twigs 2.0.0-beta.9+1.19-fabric
	- twilightforest 4.2.299
	- untitledduckmod 0.6.1
	- vanilla_degus 1.3.2
	- voidz 1.0.9
	- waterdripsound 1.19-0.3.0
	- windchimes 1.2.1
	- wondrouswilds 1.19-1.1.2
	- worldedit 7.2.12+6240-87f4ae1
	- wwoo 3.1.7
	- xaerominimap 22.15.0
	- xaeroworldmap 1.28.0
</code></pre>
</details>
[2022-09-30-7.log](https://github.com/MehVahdJukaar/SnowySpirit/files/9683097/2022-09-30-7.log)

**Comment by MehVahdJukaar** [comment]
closing this as it was fixed in newest version (forgot to reply)
