### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by MehVahdJukaar** [MehVahdJukaar/SnowySpirit#23]
1- Glow Lights don't drop when removed with shears
2- Leaves with Glow Lights have no breaking particles
3- Wild Ginger doesn't spawn
4- Gingerbread cookies always use same texture when dropped on the ground, on Item frames or on other players hands
5- Walking on top of Powdered Snow in a Sled without a Carpet doesn't freeze the player

**Comment by MehVahdJukaar** [comment]
All fixed except last one

**Comment by peow** [comment]
the last bug (walk on top of powdered snow in a sled without a carpet) is still happening (fabric 1.20.1)
![2023-11-06_19 24 08](https://github.com/MehVahdJukaar/SnowySpirit/assets/105888751/2542b8d6-a46e-4bec-9025-2cdce46b0424)

**Comment by MehVahdJukaar** [comment]
to be honest i never fixed it because i realized it didnt make much sense that player would get cold when nothing of his would be actually standing in the snow

**Comment by peow** [comment]
ok
