### ISSUE TITLE
Incompatibility with Supplementaries

### ISSUE THREAD

**Issue by Dradon7** [MehVahdJukaar/SnowySpirit#24]
When placing a supplementaries sack onto a sled, the items inside the sack are deleted.

Versions:
Minecraft: 1.19.2
Forge: 43.1.43
Supplementaries: 1.5.13
Snowy Spirit: 2.0.7

How to replicate:
- Place a sack, then place a sled next to it.
- Put some items into the sack.
- Break the sack 
- Place the filled sack onto the back of the sled
- The sack is now empty

**Comment by MehVahdJukaar** [comment]
Fixed
