### ISSUE TITLE
Failed to load Snowy Spirit (Tinted mod Incompatibility)

### ISSUE THREAD

**Issue by Jukabofy** [MehVahdJukaar/SnowySpirit#25]
[crash-2022-11-07_17.57.04-fml.txt](https://github.com/MehVahdJukaar/SnowySpirit/files/9956182/crash-2022-11-07_17.57.04-fml.txt)

**Comment by MehVahdJukaar** [comment]
It's an crash with tinted mod

**Comment by Jukabofy** [comment]
then, is a incompatibility, is the only mod crashing with tinted

**Comment by MehVahdJukaar** [comment]
All mods that assume colours are 16 or that expect such colored blocks like carpets to be from vanilla by acces registering (which by lack of API is the only way to do things like that) will require direct integration to tell them where those new carpets, beds and such are. Other mods that don't use colours won't crash or for sure won't have compatibility with it

**Comment by Jukabofy** [comment]
oh, I should report this to the Tinted mod team I guess

**Comment by MehVahdJukaar** [comment]
Nah what I was trying to say is that it is something that has to be fixed by me but it's more of a compat thing that a fix

**Comment by MehVahdJukaar** [comment]
Should work now and support it's carpets. Note that they will have to add manual support for gumdrops and glowlights. The mod like my others register stuff for all colours but "only" adds stuff for vanilla colours. You can ask them for support

**Comment by Jukabofy** [comment]
sorry for the late response, thanks
I will check the update in an hour

**Comment by MehVahdJukaar** [comment]
Nothing to do with this mod as far as I can see. This is what I was trying to say before by nature that mod might require quite some integration on other mods and it's part to work. I can't tell which mod it's conflicting with tho

**Comment by Jukabofy** [comment]
Ok, so with the last version, it works, but missing textures for the tinted mod colors
Anyway the point is to have this mod
Thank your very much
