### ISSUE TITLE
Sleds don't play sounds 

### ISSUE THREAD

**Issue by rafaelkai** [MehVahdJukaar/SnowySpirit#26]
It would be nice if they played sounds, one when on ice and other when its on other blocks, just like the boat plays one sound when on water and other on blocks.

**Comment by MehVahdJukaar** [comment]
They already do just that

**Comment by MehVahdJukaar** [comment]
2 custom sounds

**Comment by rafaelkai** [comment]
Weird, they don't seem to play for me on 2.0.7 forge, maybe it's a mod imcompatibility.

**Comment by rafaelkai** [comment]
The command plays the sound indeed, but no luck with sleds themselves.

**Comment by MehVahdJukaar** [comment]
forge or fabric?

**Comment by rafaelkai** [comment]
They seem to play sounds when fast on snow yes, just much lower than with the command.

**Comment by MehVahdJukaar** [comment]
I increased the volume a bit
