### ISSUE TITLE
No Sleds in 1.19.2

### ISSUE THREAD

**Issue by ChrisLTheNerd** [MehVahdJukaar/SnowySpirit#33]
I am using file [snowyspirit-1.19.2-2.0.12] with Forge 43.2.0 and there are no sleds anywhere in the mod.
![2022-12-16_19 50 16](https://user-images.githubusercontent.com/50182206/208214574-e8f9a820-576a-4122-ad09-5c8165766817.png)
![2022-12-16_19 52 28](https://user-images.githubusercontent.com/50182206/208214577-badb84a0-cd60-44de-ada9-ef40e950b4e3.png)

**Comment by MehVahdJukaar** [comment]
I have no clue. Must be a mod conflict as in my pack it doesn't happen

**Comment by ChrisLTheNerd** [comment]
Sorry, my bad, they appeared after installing the supplementaries mod. I thought supplementaries was optional.

**Comment by MehVahdJukaar** [comment]
It is optional

**Comment by MehVahdJukaar** [comment]
Can you check if latest version works?

**Comment by ChrisLTheNerd** [comment]
There are still no sleds without the Supplementaries mod in the latest version of the mod [snowyspirit-1.19.2-2.0.14](https://www.curseforge.com/minecraft/mc-mods/snowy-spirit/files/4191567)

This is with Supplementaries
![2022-12-18_15 16 12](https://user-images.githubusercontent.com/50182206/208317401-39b8fc04-8da6-47b1-9c3c-f15e266002cc.png)

And this is without
![2022-12-18_15 14 20](https://user-images.githubusercontent.com/50182206/208317357-b22c1428-90fd-478e-b6e4-1192f667c8ed.png)

**Comment by MehVahdJukaar** [comment]
Fixed
