### ISSUE TITLE
Axes don't work

### ISSUE THREAD

**Issue by YumatanGames** [MehVahdJukaar/SnowySpirit#52]
After installing this mod on my new modpack I'm building for myself on 1.20, for some reason, axes no longer work to break wood faster. It's the same speed as without the axe. It took me a while to figure it out what was happening, as there's no obvious reason as to why, so I had to painstakingly disable mod by mod until I found out that removing SnowSpirit fix the issue.

This is the modlist with SnowSpirit disabled:

Mods:
  [✔] (Fabric)SimpleMango-1.20-1.3.1
  [✔] 3dskinlayers-fabric-1.5.3-mc1.20
  [✔] ACE-2.0.5
  [✔] advancednetherite-fabric-2.0.2-1.20
  [✔] adventurez-1.4.18
  [✔] AirHop-v7.0.0-1.20-Fabric
  [✔] alternate-current-mc1.20-1.6.0
  [✔] AmbientEnvironment-fabric-1.20-10.0.0.2
  [✔] AmbientSounds_FABRIC_v5.2.19_mc1.20
  [✔] amecs-1.3.9+mc.1.20-pre2
  [✔] animal_feeding_trough-1.0.3+1.20
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] ArcaneLanterns-v7.0.0-1.20-Fabric
  [✔] archeologyplus-1.0.1
  [✔] architectury-9.0.8-fabric
  [✔] autosmeltenchant-1.3.0
  [✔] AxesAreWeapons-1.6.5-fabric-1.19.3
  [✔] axolotlbuckets-1.2.0+1.20
  [✔] azurelib-fabric-1.20-1.0.14
  [✔] babiesforever-1.1.0+1.20
  [✔] badpackets-fabric-0.4.1
  [✔] balm-fabric-1.20-7.0.3
  [✔] BarteringStation-v7.0.0-1.20-Fabric
  [✔] bclib-3.0.3
  [✔] betterallay-[FABRIC]-1.4.0-1.20
  [✔] betterarcheology-1.0.1
  [✔] bettermounthud-1.2.2
  [✔] better-nether-9.0.2
  [✔] bettersafebed-fabric-1.20-8
  [✔] BetterTridents-v7.0.0-1.20-Fabric
  [✔] bettertrims-1.0.1
  [✔] biomemakeover-FABRIC-1.20.0-1.10.0
  [✔] biomemoss-1.1.0
  [✔] biome-sniffer-1.2-BETA+1.20
  [✔] BlockRunner-v7.0.1-1.20-Fabric
  [✔] blossom-fabric-1.20-pre4-1.0.7
  [✔] blur-3.1.0
  [✔] Bovines-And-Buttercups-Fabric-1.6.1+1.20
  [✔] brrp-fabric-1.0.0-1.20.1
  [✔] c2me-fabric-mc1.20-0.2.0+alpha.10.87
  [✔] caffeinated-1.0.1
  [✔] capes-1.5.2+1.20-fabric
  [✔] cat_jam-1.0.2
  [✔] chat_heads-0.10.15-fabric-1.20
  [✔] cherish-1.2.0
  [✔] chunksfadein-v1.0.1-1.20
  [✔] CITResewn-1.1.3+1.20
  [✔] CleanF3-0.4.0-mc1.20
  [✔] cloth-config-11.0.99-fabric
  [✔] clutter-1.20-0.3.4
  [✔] collective-1.20.0-6.57
  [✔] compact-chat-2.0.1
  [✔] CompletionistsIndex-v7.0.0-1.20-Fabric
  [✔] conduitspreventdrowned-1.20.0-3.4
  [✔] continuebutton-1.1.1+1.20
  [✔] continuity-3.0.0-beta.2+1.20
  [✔] Controlling-fabric-1.20-12.0.2
  [✔] copperhopper-0.3.0+1.20.0
  [✔] cozy-1.1.0-fabric
  [✔] CreativeCore_FABRIC_v2.10.23_mc1.20
  [✔] CreativeOnePunch-1.3-universal
  [✔] Croptopia-1.20-FABRIC-2.2.2
  [✔] cryingportals-1.20.0-2.3
  [✔] ctov-3.3.0
  [✔] CullLessLeaves-1.2.0
  [✔] cyclepaintings-1.20.0-3.2
  [✔] dark-waters-1.20-0.0.18
  [✔] DeathFinder-v7.0.0-1.20-Fabric
  [✔] Debugify-1.20+1.1
  [✔] deeper-oceans-mc1.20-v1.0.1a
  [✔] DiagonalFences-v7.0.0-1.20-Fabric
  [✔] dimensional-anchor-1.20-1.0.2
  [✔] do-a-barrel-roll-3.0.1+1.20-fabric
  [✔] doubledoors-1.20.0-4.5
  [✔] DramaticDoors-Fabric-1.20-2.0.0
  [✔] DripSounds-1.19.4-0.3.2
  [✔] dungeons-and-taverns-v2.1.2
  [✔] durabilityplus_1.19-1.20_1.0.2
  [✔] dynamiccrosshair-7.0.2+1.20-fabric
  [✔] dynamic-fps-2.3.0
  [✔] earth2java-fabric-1.10.1+1.20
  [✔] EasyAnvils-v7.0.0-1.20-Fabric
  [✔] EasyMagic-v7.0.0-1.20-Fabric
  [✔] EasyShulkerBoxes-v7.0.0-1.20-Fabric
  [✔] eating-animation-1.9.4+1.20
  [✔] EchoChest-v7.0.1-1.20-Fabric
  [✔] elytratrims-1.1.5+1.20
  [✔] EnchantingInfuser-v7.0.0-1.20-Fabric
  [✔] enchantmentcompat-1.2.1+1.20
  [✔] EnderZoology-v7.0.0-1.20-Fabric
  [✔] entity_model_features_fabric_1.20-0.2.10
  [✔] entity_texture_features_fabric_1.20-4.4.4
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] exit-confirmation-2.4.0-mc.1.20
  [✔] extendedclouds-1.2.2+1.20
  [✔] extended-copper-1.4.1-1.20
  [✔] extshape-fabric-2.0.1-mc1.20.1
  [✔] fabric-api-0.83.0+1.20
  [✔] fabric-language-kotlin-1.9.5+kotlin.1.8.22
  [✔] fabric-seasons-2.2.1+1.20
  [✔] fabric-seasons-extras-1.2-BETA+1.20
  [✔] fabricskyboxes-0.7.1+mc1.20
  [✔] fallingleaves-1.15.0+1.19.4
  [✔] fansmod-1.20-2.0.1.2
  [✔] ferritecore-6.0.0-fabric
  [✔] fish_of_thieves-mc1.20-v3.0.0-fabric
  [✔] fluidvoidfading-1.1.0
  [✔] FogLooksGoodNow-1.2.0+1.20
  [✔] food-plus-2.1+1.20
  [✔] ForgeConfigAPIPort-v7.0.0-1.20-Fabric
  [✔] gamma_shifter-1.0.1+mc1.20
  [✔] Gamma-Utils-1.7.14-mc1.20
  [✔] geckolib-fabric-1.20-4.2
  [✔] Grass_Overhaul-Fabric-23.06.09_MC1.20
  [✔] gravelminer-fabric-1.20-16.0.1
  [✔] graves-3.0.0-beta.2+1.20
  [✔] grind-enchantments-3.1.2+1.20
  [✔] handcrafted-fabric-1.20-2.3.2
  [✔] head_in_the_clouds-1.0.0
  [✔] IllagersWearArmor-1.1.0+1.20
  [✔] ImmediatelyFast-1.1.15+1.20.1
  [✔] imst-2.1.0
  [✔] indium-1.0.18+mc1.20
  [✔] inventoryfullalert-1.2.1-1.20
  [✔] InventorySorter-1.8.10-1.20
  [✔] iris-mc1.20-1.6.4
  [✔] Jade-1.20-fabric-11.1.0
  [✔] jei-1.20-fabric-14.0.0.11
  [✔] JustMoreCakes-fabric-1.20-1.12.1
  [✔] krypton-0.2.3
  [✔] leashablevillagers-1.0-mc1.20
  [✔] LeavesBeGone-v7.0.0-1.20-Fabric
  [✔] linkart-5.1.1-1.19.3
  [✔] lithium-fabric-mc1.20-0.11.2
  [✔] LostFeatures-fabric-1.20-0.7.1
  [✔] make_bubbles_pop-0.1.1
  [✔] mavapi-1.1.0-mc1.20
  [✔] mavm-1.2.3-mc1.20
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] midnightlib-fabric-1.4.1.1
  [✔] mixintrace-1.1.1+1.17
  [✔] mob-captains-v2.1.2
  [✔] MobPlaques-v7.0.0-1.20-Fabric
  [✔] mobs-attempt-parkour-0.5-1.20
  [✔] modmenu-7.0.1
  [✔] monsters-in-the-closet-1.0.3+1.20
  [✔] moonlight-1.20-2.5.3-fabric
  [✔] mooshroomtweaks-1.20.0-3.2
  [✔] more-amethyst-recipes-1.0
  [✔] morebannerfeatures-1.2.0-1.20
  [✔] MoreBows-1.0.11+1.20.x
  [✔] more-mobs-1.4
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] more-totems-mod-2.15.0
  [✔] mossier-deepslate-1.20-2.0.2
  [✔] mousewheelie-1.11.1+mc1.20-pre2
  [✔] MutantMonsters-v7.0.0-1.20-Fabric
  [✔] NetherChested-v7.0.0-1.20-Fabric
  [✔] nicerportals-1.2.1+1.20
  [✔] nnvf-0.1.3_1.20
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.1
  [✔] no-more-purple-1.2.0+1.20
  [✔] no-resource-pack-warnings-1.3.0
  [✔] Notebook-3.0.0+1.20
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] npc-variety-1.20-2.3.0
  [✔] numeralping-1.2.1
  [✔] ocrenderfix_sodium-fabric-1.1.0
  [✔] OEM-1.0.7-1.20
  [✔] optigui-2.1.2
  [✔] origamikings-api-0.1.11-1.20
  [✔] ottah-A2-pre_1
  [✔] OverflowingBars-v7.0.0-1.20-Fabric
  [✔] OverpoweredMending-1.20-2.11.0
  [✔] owo-lib-0.11.0+1.20
  [✔] ParticleTweaks-1.1-Fabric+1.20-pre2-unstable
  [✔] PermanentSponges-v7.0.0-1.20-Fabric
  [✔] Philips-Ruins1.20-1.0[Fabric]
  [✔] physics-mod-pro-v155-fabric-1.20
  [✔] PickUpNotifier-v7.0.0-1.20-Fabric
  [✔] polaroidcamera-1.6.1
  [✔] PresenceFootsteps-1.9.0
  [✔] prettybeaches-fabric-1.20-11.0.0
  [✔] puzzle-1.5.1+1.20
  [✔] PuzzlesLib-v7.0.3-1.20-Fabric
  [✔] reacharound+1.20-1.1.2
  [✔] realisticbees-1.20.0-3.4
  [✔] recipe-book-is-pain-0.9.3-1.20
  [✔] reeses_sodium_options-1.5.1+mc1.20-build.74
  [✔] RegionsUnexploredFabric-0.4.1+1.20
  [✔] reinforced-barrels-2.4.0+1.20
  [✔] reinforced-chests-2.4.0+1.20
  [✔] repurposed_structures-7.0.0+1.20-fabric
  [✔] resourcefullib-fabric-1.20-2.0.7
  [✔] Retraining-fabric-1.20-1.3.0
  [✔] scaffoldingdropsnearby-1.20.0-3.0
  [✔] screenshot-to-clipboard-1.0.9-fabric
  [✔] seamless-1.3.0-fabric-1.19.2
  [✔] Searchables-fabric-1.20-1.0.2
  [✔] sheets-1.3
  [✔] shulkerboxtooltip-fabric-4.0.2+1.20
  [✔] shulkerdropstwo-1.20.0-3.1
  [✔] simplefog-1.4.0
  [✔] simplekelpies-1.1.0
  [✔] sit-1.20-24
  [✔] six-stairs-mcmeta-4_1.20
  [✔] sleep_tight-1.20-1.1.1-fabric
  [✔] smallships-fabric-1.20-2.0.0-a2.3.2
  [✔] SmartBrainLib-fabric-1.20-1.11
  [✔] Sniffer+-fabric-1.20-0.1.0
  [✔] snow-under-trees-fabric-1.1.0+1.20
  [✘] snowyspirit-1.20-2.2.0-fabric.jar (disabled)
  [✔] sodium-extra-0.4.20+mc1.20-build.103
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] soundphysics-fabric-1.20-1.1.1
  [✔] spyglass_astronomy-1.0.5-mc1.20+
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] stendhal-1.3.8-1.20
  [✔] Stoneworks-v7.0.0-1.20-Fabric
  [✔] StylishEffects-v7.0.0-1.20-Fabric
  [✔] subterrestrial-fabric-1.20-2.2.0
  [✔] superflatworldnoslimes-1.20.0-3.0
  [✔] supplementaries-1.20-2.5.2-fabric
  [✔] swampier_swamps-1.20-4.0.0
  [✔] swingthrough-1.0.2+1.19
  [✔] symbol-chat-1.20-1.0.0
  [✔] TaxFreeLevels-1.3.3-fabric-1.19
  [✔] TerraBlender-fabric-1.20-3.0.0.163
  [✔] TinySkeletons-v6.0.0-1.20-Fabric
  [✔] toggleableitemframes-2.1.2-1.20
  [✔] totem_anywhere-1.1.4+1.19.2
  [✔] TradingPost-v7.0.0-1.20-Fabric
  [✔] transcendingtrident-1.20.0-4.2
  [✔] travelers-backpack-1.20-9.0.2
  [✔] trimmable-tools-mc1.20-v1.0.4
  [✔] UniversalBoneMeal-v7.0.0-1.20-Fabric
  [✔] Variety_Aquatic-fabric-1.0.4.6
  [✔] VarietyAPI-Fabric-1.0
  [✔] villagernames-1.20-4.5.1
  [✔] VillagersPlus_1.11_(FABRIC)_for_1.20
  [✔] visuality-0.7.0+1.20
  [✔] VisualWorkbench-v7.0.0-1.20-Fabric
  [✔] Void-Fog-2.10.0
  [✔] vorpal-enchantment-1.20-3.0.3
  [✔] Weeping-Angels-46.0.0-fabric
  [✔] wetlavasponge-1.0.1
  [✔] WilderWild-2.0.4-Fabric+1.20
  [✔] windchimes-1.2.3+1.20
  [✔] wraith-harvestscythes-2.5.6+mc1.20
  [✔] Xaeros_Minimap_23.4.4_Fabric_1.20
  [✔] XaerosWorldMap_1.30.4_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.0.1+1.20
  [✔] YouDied-1.20-3.0.0.17-fabric
  [✔] youritemsaresafe-1.20.0-3.3
  [✔] Zoomify-2.10.0

**Comment by mosharky** [comment]
Happens to me as well on Forge. Broke it down to this mod.

**Comment by MehVahdJukaar** [comment]
fixed in latest version
